/*
 * Copyright (C) 2023 Cobblemon Contributors
 *
 * This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at https://mozilla.org/MPL/2.0/.
 */

package com.cobblemon.mod.common.client.render.item

object PokePuffItemModelRegistry {
    private val modelMap = mapOf(
        "overlay_spicy" to 0.001f,
        "overlay_spicy_only" to 0.002f,
        "overlay_spicy_strawberry" to 0.003f,
        "overlay_dry_only" to 0.004f,
        "overlay_spicy_love" to 0.005f,
        "overlay_sweet_only" to 0.006f,
        "overlay_spicy_berry" to 0.007f,
        "overlay_bitter_only" to 0.008f,
        "overlay_spicy_ribbon" to 0.009f,
        "overlay_sour_only" to 0.010f,
        "overlay_spicy_clover" to 0.011f,
        "overlay_mild_only" to 0.012f,
        "overlay_spicy_flower" to 0.013f,
        "overlay_plain_only" to 0.014f,
        "overlay_spicy_star" to 0.015f,
        "overlay_dry" to 0.016f,
        "overlay_dry_strawberry" to 0.017f,
        "overlay_dry_love" to 0.018f,
        "overlay_dry_berry" to 0.019f,
        "overlay_dry_ribbon" to 0.020f,
        "overlay_dry_clover" to 0.021f,
        "overlay_dry_flower" to 0.022f,
        "overlay_dry_star" to 0.023f,
        "overlay_sweet" to 0.024f,
        "overlay_sweet_strawberry" to 0.025f,
        "overlay_sweet_love" to 0.026f,
        "overlay_sweet_berry" to 0.027f,
        "overlay_sweet_ribbon" to 0.028f,
        "overlay_sweet_clover" to 0.029f,
        "overlay_sweet_flower" to 0.030f,
        "overlay_sweet_star" to 0.031f,
        "overlay_bitter" to 0.032f,
        "overlay_bitter_strawberry" to 0.033f,
        "overlay_bitter_love" to 0.034f,
        "overlay_bitter_berry" to 0.035f,
        "overlay_bitter_ribbon" to 0.036f,
        "overlay_bitter_clover" to 0.037f,
        "overlay_bitter_flower" to 0.038f,
        "overlay_bitter_star" to 0.039f,
        "overlay_sour" to 0.040f,
        "overlay_sour_strawberry" to 0.041f,
        "overlay_sour_love" to 0.042f,
        "overlay_sour_berry" to 0.043f,
        "overlay_sour_ribbon" to 0.044f,
        "overlay_sour_clover" to 0.045f,
        "overlay_sour_flower" to 0.046f,
        "overlay_sour_star" to 0.047f,
        "overlay_mild" to 0.048f,
        "overlay_mild_strawberry" to 0.049f,
        "overlay_mild_love" to 0.050f,
        "overlay_mild_berry" to 0.051f,
        "overlay_mild_ribbon" to 0.052f,
        "overlay_clover" to 0.053f,
        "overlay_mild_clover" to 0.054f,
        "overlay_flower" to 0.055f,
        "overlay_mild_flower" to 0.056f,
        "overlay_star" to 0.057f,
        "overlay_mild_star" to 0.058f,
        "overlay_plain" to 0.059f,
        "overlay_strawberry" to 0.060f,
        "overlay_plain_strawberry" to 0.061f,
        "overlay_love" to 0.062f,
        "overlay_plain_love" to 0.063f,
        "overlay_berry" to 0.064f,
        "overlay_plain_berry" to 0.065f,
        "overlay_ribbon" to 0.066f,
        "overlay_plain_ribbon" to 0.067f,

        "overlay_strawberry_spicy" to 0.068f,
        "overlay_strawberry_dry" to 0.069f,
        "overlay_strawberry_sweet" to 0.070f,
        "overlay_strawberry_bitter" to 0.071f,
        "overlay_strawberry_sour" to 0.072f,
        "overlay_strawberry_mild" to 0.073f,
        "overlay_strawberry_plain" to 0.074f,

        "overlay_love_spicy" to 0.075f,
        "overlay_love_dry" to 0.076f,
        "overlay_love_sweet" to 0.077f,
        "overlay_love_bitter" to 0.078f,
        "overlay_love_sour" to 0.079f,
        "overlay_love_mild" to 0.080f,
        "overlay_love_plain" to 0.081f,

        "overlay_berry_spicy" to 0.082f,
        "overlay_berry_dry" to 0.083f,
        "overlay_berry_sweet" to 0.084f,
        "overlay_berry_bitter" to 0.085f,
        "overlay_berry_sour" to 0.086f,
        "overlay_berry_mild" to 0.087f,
        "overlay_berry_plain" to 0.088f,

        "overlay_ribbon_spicy" to 0.089f,
        "overlay_ribbon_dry" to 0.090f,
        "overlay_ribbon_sweet" to 0.091f,
        "overlay_ribbon_bitter" to 0.092f,
        "overlay_ribbon_sour" to 0.093f,
        "overlay_ribbon_mild" to 0.094f,
        "overlay_ribbon_plain" to 0.095f,

        "overlay_clover_spicy" to 0.096f,
        "overlay_clover_dry" to 0.097f,
        "overlay_clover_sweet" to 0.098f,
        "overlay_clover_bitter" to 0.099f,
        "overlay_clover_sour" to 0.100f,
        "overlay_clover_mild" to 0.101f,
        "overlay_clover_plain" to 0.102f,

        "overlay_flower_spicy" to 0.103f,
        "overlay_flower_dry" to 0.104f,
        "overlay_flower_sweet" to 0.105f,
        "overlay_flower_bitter" to 0.106f,
        "overlay_flower_sour" to 0.107f,
        "overlay_flower_mild" to 0.108f,
        "overlay_flower_plain" to 0.109f,

        "overlay_star_spicy" to 0.110f,
        "overlay_star_dry" to 0.111f,
        "overlay_star_sweet" to 0.112f,
        "overlay_star_bitter" to 0.113f,
        "overlay_star_sour" to 0.114f,
        "overlay_star_mild" to 0.115f,
        "overlay_star_plain" to 0.116f,

        "overlay_plain_clover" to 0.117f,
        "overlay_plain_flower" to 0.118f,
        "overlay_plain_star" to 0.119f
    )

    fun getModelId(key: String): Float {
        return modelMap[key] ?: 0.0f
    }
}